// components/icons.tsx
// Centralized export for lucide-react icons used in the application.

export {
  // Sidebar & Modes
  MessageSquare,
  BrainCircuit,
  Globe,
  MapPin,
  Image,
  Film,
  Mic,
  Clapperboard,
  PenSquare,
  Video,
  Bot,
  BookOpen,
  ScrollText,
  Scale,
  Landmark,
  Globe2,
  Newspaper,
  BookMarked,
  Mountain,
  SquarePen,
  FileCheck,
  ListChecks,
  BookCopy,
  SearchCode,
  DraftingCompass,
  NotebookText,
  CalendarDays,
  Binary,
  MessageCircleQuestion,
  Phone,
  Users,
  FolderKanban,
  UploadCloud,
  FileText,
  Trash2,
  Wand2,
  FileQuestion,

  // UI Controls
  Plus,
  // FIX: Export `PlusCircle` to resolve import error in ProjectApp/Index.tsx.
  PlusCircle,
  ChevronDown,
  ArrowUp,
  Paperclip,
  X,
  Check,
  Play,
  StopCircle,
  ArrowRight,
  PanelLeftClose,
  PanelLeftOpen,
  PanelLeft,
  PanelRight,
  ChevronRight,
  Menu,
  LayoutGrid,
  Search,
  Link,
  Layers,
  // FIX: Export missing icons for MindmapApp.
  Minus,
  ZoomIn,
  ZoomOut,
  CornerDownLeft,
  File,
  FilePlus,
  Share,
  Network,
  Locate,
  // New icons for mindmap toolbar
  Undo,
  Redo,
  FilePenLine,
  // New icons for mindmap
  Palette,
  Download,
  FileCode,
  StickyNote,

  // Message Display
  Sparkles,
  User,
  Volume2,
  Zap,
  // FIX: Export icons for Mindmap Context Menu
  CheckSquare,
  ClipboardList,
  Tag,
  FunctionSquare,
  // New icons for Theme Toggle
  Sun,
  Moon,
  Clock,
} from 'lucide-react';